README.md

When viewing this README in other repositories, such as drud-go, the context for the subtree merge instructions are not immediately clear. This is handled via examples and headers in other files, but since the README is likely the first thing people would look at, we should make sure to explicitly call it out there as well.

Give context on where the build-tools live

---

README.md
build_update.sh

Issue: https://github.com/drud/general/issues/17 (Overall build system for drud projects)
The subtree merge technique did not work in practice. The build_update.sh script here can do an add or update and commit the results.

Add new build-tools update technique - build_update.sh

---

README.md
build-scripts/build_go.sh
build-scripts/test_go.sh
makefile_components/base_build_go.mak
makefile_components/base_container.mak

This PR 
* switches to use our own intermediate golang container instead of using the direct golang official container.
* Adds the vendorcheck and govendor tools
* Moves gofmt/govendor tests to the build/compile phase instead of the test target
* Adds vendorcheck and govendor list +unused
* Adds repo_name_VERSION_INFO.txt into dockerfile with git commit info
The reason for moving the gofmt and related to the build target is that we sometimes test directly (rather than in the container) so those checks were being skipped when the test target was overrridden. But we always build in the container. 
The extended checks can be overridden with EXTENDED_CHECKS=true either in environment or on make invocation.
Testing suggestions:
* Install this version of build-tools into a golang project with a …

Change to our own container, move checks from test to build target

---

README.md
build-scripts/build_go.sh
circle.yml.example
makefile_components/base_build_go.mak

This moves the static analysis tools into separate targets, no variable now needed. The check can be included in circle.yml, but need not slow down ordinary compiles.
```
make gofmt
make golint
make vendorcheck
make govet
make static (all 4)
make gofmt vendorcheck govet (standard check)
```

Separate static analysis tools into new targets

---

Makefile.example
makefile_components/base_build_go.mak
makefile_components/base_test_go.mak
tests/Makefile

I introduced basic build and testing problems in https://github.com/drud/build-tools/pull/5 - this fixes them.
* Separates ldflags from the VERSION_LDFLAGS
* Adds ldflags to test as well as compile
* Makes the darwin build work again
Testing: This is introduced into ddev in https://github.com/drud/ddev/pull/25 - So that's a practical example. I will also begin adding basic test capabilities in a separate PR.
Automated testing requires:
I'm not sure there would be a way to generate and detect a bad version, but the test should be written to do that.

Fix broken linking behavior introduced with VERSION_LDFLAGS changes

---

build_update.sh

I noticed when updating ddev that the build-tools circle.yml (which as always is in top level) was left in there, which could confuse somebody in the future. This removes it during the installation with the script.

Remove build-tools circle.yml when updating, as it isn't relevant

---

makefile_components/base_container.mak

The failed write of "\n\n" in .docker-image resulted in a circle.yml usage failure elsewhere. This is a fairly trivial problem and can be solved elsewhere, but that "\n\n" shouldn't be in .docker-image anyway.

Remove failed newlines from .docker_image

---

makefile_components/base_build_go.mak

Researching @beeradb 's problems in build I noted that there are nested single quotes in the build statement - I am not sure how it could work with those in there. I don't think this is related to his occasional build oddities, but it needs to be fixed.

Remove spurious single-quotes in golang build statement

---

makefile_components/base_build_go.mak
makefile_components/base_test_go.mak

We are leaving lots of golang-build-container 's around, and it makes no sense to do that. Instead we should use the --rm flag on our docker invocations. Thanks @beeradb

Use --rm on docker commands

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
build_update.sh

This just adds .github from ddev (and rm's it on deployment)

Add github issue status to build-tools

---

build_update.sh

It's useful to know what version of build-tools a project currently has installed, and it's not easy to know it right now.
Add a version file.
#13 requested this feature.

Fixes #13 by adding a version file on update

---

makefile_components/base_build_go.mak
makefile_components/base_build_python-docker.mak
tests/pkg/clean/build_tools_test.go
tests/pkg/dirtyComplex/bad_errcheck_code.go
tests/pkg/dirtyComplex/bad_staticcheck_code.go
tests/pkg/dirtyComplex/bad_unused_code.go

Build container has been updated to v0.2.0 for golang 1.8.1, see https://github.com/drud/golang-build-container/pull/1
* Change the tag we use. 
* Add more static analysis targets, especially errcheck
A provisional v0.2.0 has been pushed to drud/golang-build-container
https://github.com/drud/golang-build-container/pull/1

Bump golang-build-container to v0.2.0, add static analysis targets

---

README.md
makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go

It's nice to detect unused code. Currently we have a `make unused` target, but that doesn't appear to get exported functions. Code coroner (https://github.com/3rf/codecoroner) does, and from my tests against ddev appears to work fairly well.
Add a `codecoroner` build target, as well as tests to support them
Simply run `make codecoroner` against the tests in this repo, and you'll see it rightfully complain that much of the code is not used.
There are automated tests for this in the `TestCodeCoroner` function which were derived from the existing tests for the `unused` target.
I've pushed a provisional `codecoroner` tag for the build container to docker hub. If the code here looks good, we need to:

Add codecoroner build target

---

README.md
gitignore.example
tests/.gitignore

The default gitignore was ignoring files it shouldn't, especially in some container repos (See #18)
* Prefix paths with /
* Add comment to say that the gitignore goes with the Makefile

Make gitignore.example more explicit - fixes #18

---

makefile_components/base_build_go.mak
makefile_components/base_test_go.mak
tests/Makefile
tests/cmd/build_tools_dummy/build_tools_dummy.go
tests/pkg/clean/build_tools_test.go
tests/pkg/version/version.go

It would be nice to know explicit information about *commit* and *build date/time/context* from an actual executable.  
Note that currently version.VERSION *can* be the commit, but it's overridden by $(VERSION), which makes things a bit untraceable when you use `make VERSION=something`, so this makes the commit explicit.
Add these items to build-tools.
Testing is added to TestBuild for these
* If the `make test` target is overridden in build-tools, it may need to have double-quotes changed to single-quotes around the LDFLAGS, as in the Makefile in tests here. For example:  `go test -v -installsuffix "static" -ldflags '$(LDFLAGS)' $(SRC_AND_UNDER) $(TESTARGS)`
* To make …

Add buildinfo date/context to standard build

---

makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go
tests/pkg/dirtyComplex/bad_misspell_code.go

gometalinter is now included in the golang_build_container, we'd like to have it easily available.
* Bump default version of drud/golang_build_container
* Add gometalinter target
* Provide $(GOMETALINTER_ARGS) which can be overridden in any Makefile or on command line. (but defaults to fairly sane set)
* Quiet the linters down a bit (we don't need to see their docker commands) and make them output a newline after each one.
* Add a trivial test for `make gometalinter`
* Clean up some errors discovered in tests (many were testing unused when they weren't supposed to. Copy/paste error.
This just adds a trivial test for the gometalinter target.

Add gometalinter into build tools

---

gitignore.example
makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go

We're flirting with Windows support for ddev, and it's easy enough to *build* for windows. Add the target and clean.
Ad the target and clean.

Add windows target and clean

---

README.md

The readme still references subtree merges, which is now an outdated technique. Let's remove the reference.

Update the readme to remove outdated subtree merge reference

---

makefile_components/base_test_go.mak

A backslash was tragically lost, breaking the default `make test` behavior for golang building.
Add the backslash back

Add missing backslash in base_test_go

---

makefile_components/base_test_go.mak
tests/Makefile
tests/standard_target/.gitignore
tests/standard_target/Makefile
tests/standard_target/cmd/main.go
tests/standard_target/cmd/main_test.go

Over in 8e7d62f2 https://github.com/drud/build-tools/pull/21 I made a silly edit to the default test target which completely broke lots of things. You can't set $GOOS for a test, because you'll get crazy errors like this:
```
fork/exec /tmp/go-build380509523/github.com/drud/elysium/pkg/elysium/_test/elysium.test: exec format error
FAIL	github.com/drud/elysium/pkg/elysium	0.009s
```
Go test has to run what it compiles on the environment it compiled for, not something else. We were trying to test darwin build on a linux machine.
Remove the GOOS setting from the default golang test target.

Remove inappropriate GOOS statement since we can't cross-compile test

---

gitignore.example
makefile_components/base_build_go.mak
makefile_components/base_build_python-docker.mak
makefile_components/base_test_go.mak
tests/.gitignore
tests/Makefile
tests/standard_target/.gitignore

The up-and-coming golang dep tool, which will solve most of the world's problems, appears to use .go, which conflicts with our usage. We'd like to step out of the way.
Parameterize the tmp .go directory, and then handle it. It becomes .gotmp
Should be fine if it passes existing tests.
Fixes #11

Step away from using .go since dep will use it, fixes #11

---

makefile_components/base_build_go.mak

golang has moved along to v1.8.3 - there's not a lot of change, but it's worth keeping up.
Upgrade.
https://github.com/drud/golang-build-container/pull/5 is the upgrade for golang-build-container. It needs to be tagged, then this one can be tagged with another commit and we'll be there.
This is currently using the provisional tag (manually pushed). When the real push is done from a tagged release on golang_build_container then we can just add a commit to this with the real tag, then create a release.

Upgrade to golang 1.8.3

---

makefile_components/base_build_go.mak

When we were getting used to build-tools we had the full make build output going on, and it's a doozie, with all that docker nonsense.
We don't need to see all that any more.
Put an @ in front of the build command.

Quiet builds - we don't need to see docker any more

---

makefile_components/base_test_go.mak
tests/Makefile

Our tests can have outright syntax errors in them, but we don't find out about it until we do a full test run, as each package's tests are only compiled when its tests are run. This is particularly painful when doing a large-ish refactor and you make little mistakes with imports and such, but don't find out until a full test.
This adds a test_precompile target (`make test_precompile`) which easily builds all the tests without running them. However, all code in TestMain gets run so it can slow things down. The test_precompile time for ddev is almost a minute.
**Note: This is already easily available in (almost?) all usages of build-tools with `make test TESTARGS='-run "^$$"'`**
Does this affect anything else, or are there ramifications for other code? Does anything have to be done on …

Add test_precompile target to compile but not run tests

---

build_update.sh

When circle.yml moved to .circleci, build-tools didn't catch it, so build-tools' own .circleci folder is not being deleted on install.
Add it to the removal in the script.

Remove .circleci on install

---

makefile_components/base_push.mak

It seems the push component was using gcloud to push to docker. Not should be that way.
Just use docker.

We shouldn't be using gcloud to push to docker

---

build_update.sh

The build-tools appveyor config can get introduced inappropriately into another repo.
Remove it on install.

Remove appveyor config when deploying on another repo

---

makefile_components/base_build_go.mak
tests/Makefile
tests/pkg/clean/build_tools_test.go
tests/pkg/clean/simple_successful_unit_test.go

Golang 1.9.0 is out, we should probably start using it.
This will need to have a followup commit pointing to an official drud/golang-build-tools when that goes in.

Upgrade to golang 1.9.0

---

circleci-config-yaml.example
makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go

We have a nice ['staticrequired' target added to ddev](https://github.com/drud/ddev/blob/master/Makefile#L92). We should run those tools in the 'static' target provided by build-tools, and update the example circle config to use the static target instead of calling tool-specific targets. This should help ensure new go projects get the same testing treatment that ddev and others have been set up with.
This does that.

replace static target with gometalinter, update circle cfg example to use it

---

Makefile.example

Originally, the Makefile.example gave hard-wired in-Makefile VERSION hint, but we normally really really want to tie VERSION to git version/tag except when making rapid changes, when it can be overridden on the command line.
This just removes the suggestion of a fixed VERSION in the Makefile. It does some trivial cleanup of example and comment along the way.
This changes nothing, just the example.

Remove hard-wired VERSION from Makefile.example as git-tied VERSION serves well

---

makefile_components/base_build_go.mak

https://github.com/drud/build-tools/pull/42 added/improved gometalinter capabilities, but when adding that to ddev I noted that we really would like shadow warnings, as vetshadow provides.  That's easy to do (as done over there with changing GOMETALINTERARGS, but it seems best to change the default GOMETALINTERARGS here.

Add vetshadow to default stable of gometalinter tools

---

makefile_components/base_build_go.mak

We've bumped the golang-build-container to v0.5.1 to get golang 1.9.1
This is a one-character PR :)

Upgrade golang-build-container to v0.5.1-golang 1.9.1

---

makefile_components/base_build_go.mak
makefile_components/base_test_go.mak

Big builds were taking way long. The most likely culprit was the performance of the mount. But since we only care about what's in the container during the build, we can use the :delegated flag.
This adds the :delegated flag to mounts on the golang-build-container

Add docker mount flag :delegated to mounts

---

.circleci/config.yml
makefile_components/base_build_go.mak

In https://github.com/drud/build-tools/pull/46 I added the structure for providing a docker mount flag (:delegated) but failed to actually supply it. This fixes that fail. Glad you caught it Tanner even though my trigger finger was too fast.

Actually use the docker mount :delegated flag

---

Makefile.example

Just a little thing to hopefully avoid trouble down the road setting up project makefiles from the example. An indentation in our example makefile causes editors to detect 2-space indentation, when we want tabs instead for makefiles.
Converted indentation to tabs in example.

update Makefile.example to indent with tabs

---

makefile_components/base_build_go.mak
makefile_components/base_build_python-docker.mak

It's time to bump golang and update the build container. https://github.com/drud/golang-build-container/pull/10
After the golang build container patch goes in, this one has to be updated with the real released image. https://github.com/drud/golang-build-container/pull/10

Bump golang-build-container to pick up go 1.9.3

---

makefile_components/base_build_go.mak
makefile_components/base_build_python-docker.mak

This updates build-tools to use v0.5.4 of the golang-build-container, which adds dep and glide dependency management tools.

updates golang-build-container to v0.5.4

---

.circleci/config.yml
makefile_components/base_build_go.mak

The golang-build-container is being upgraded to golang 1.10. This pulls that in.
In addition, since go 1.10 has far more aggressive caching, it's important to clear the *local* go cache on `make clean`. The local go is used for testing at least on ddev, so its caching sometimes really needs to go away.
Followup:

Upgrade build-tools for golang 1.10, clear cache on clean

---

makefile_components/base_build_python-docker.mak

We keep forgetting to update BUILD_IMAGE in docker-python build... but we don't even use it there. 
Remove it from that spot. I'm pretty sure it will do no harm.

Remove BUILD_IMAGE from python-docker as it's not used

---

makefile_components/base_build_go.mak

Time to move up golang version.

Bump golang-build-container to v1.10.2

---

makefile_components/base_build_go.mak

I left an '@' out of the main build command, so now `make` emits all kinds of output I didn't want to see. 
Put the @ back in.
Do a `make`. You should see a little, not a lot.

Quiet the normal build, shouldn't be emitting the whole docker build

---

makefile_components/base_container.mak
tests/Dockerfile
tests/Dockerfile.in

A regression in https://github.com/drud/build-tools/pull/56 broke `make push` by changing the artifacts in `make container`. 
* Change it back to mostly what it was.
* In addition the container build test now uses Dockerfile instead of Dockerfile.in

Fix container build so make push will work again

---

.circleci/config.yml
makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go

Golang v1.11 is out
Bump to it (in golang-build-container)

Bump to golang v1.11

---

makefile_components/base_build_go.mak

In #61 the use of $(USE_MOD_VENDOR) was dropped, meaning that a build will (successfully) download everything it (doesn't need) because it's already in vendor.
This also adds a test before pulling the build container, which should avoid unnecessary waiting.

Forgot to USE_MOD_VENDOR in #61

---

makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go

Golang 1.12 is out, upstream golang-build-tools has been updated. Bump it here.

Bump golang to 1.12

---

makefile_components/base_build_go.mak

Golang v1.12.1 is out
Update to the upstream.

Bump build_image to v1.12.1

---

build_update.sh
makefile_components/base_build_go.mak
tests/pkg/clean/build_tools_test.go

GOCACHE is mighty important. Somehow either in the flow of build-tools or the changes in golang caching, we ended up rebuilding the cache on every build.
Add GOCACHE pointing to workdir/.cache

Use GOCACHE. It was always being recreated

---

makefile_components/base_build_go.mak
tests/go.mod
tests/pkg/clean/build_tools_test.go
tests/standard_target/go.mod

Use golang v1.13 

---

.circleci/config.yml
build_update.sh
makefile_components/base_build_go.mak

Time to bump the golang container.
The build_update.sh script has been broken a long time.
Bump and fix

Bump golang to latest and fix build_update.sh
